name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: find samples -name 'Dockerfile*' | xargs -n1 -IDOCKERFILE docker build . --file DOCKERFILE --tag reprox:$(date +%s)
